name: Python CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Clone Norma.jl repository
      run: |
        git clone -n --depth=1 --filter=tree:0 -b eparish1/85-opinf-opinf https://github.com/sandialabs/Norma.jl.git
        cd Norma.jl
        git sparse-checkout set --no-cone /src /Project.toml
        git checkout


    - name: Set up Julia
      uses: julia-actions/setup-julia@v2 
      with:
        version: '1.11'  # Specify the Julia version

    - name: Cache Julia artifacts
      uses: julia-actions/cache@v2

    - name: Setup Norma 
      run: |
        cd Norma.jl 
        julia -e 'using Pkg; Pkg.activate("."); Pkg.update();'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install . 


    - name: Test cuboid 
      run: |
        cd $GITHUB_WORKSPACE/norma-regression-tests/single/cuboid/dynamic-opinf-fom
        julia --project=$GITHUB_WORKSPACE/Norma.jl $GITHUB_WORKSPACE/Norma.jl/src/Norma.jl cuboid.yaml
        python make_opinf_models.py
        python check_models.py
        cp opinf-operator.npz ../dynamic-opinf-rom
        cd ../dynamic-opinf-rom
        julia --project=$GITHUB_WORKSPACE/Norma.jl $GITHUB_WORKSPACE/Norma.jl/src/Norma.jl cuboid.yaml
        python check_solution.py 


    - name: Run tests
      run: |
        pytest  # Run tests using pytest

