name: Python CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest  # Run tests using pytest
